# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Klaiveft/EPITECH/TEK3/RTYPE/R-Type

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Klaiveft/EPITECH/TEK3/RTYPE/R-Type

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Klaiveft/EPITECH/TEK3/RTYPE/R-Type/CMakeFiles /home/Klaiveft/EPITECH/TEK3/RTYPE/R-Type//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Klaiveft/EPITECH/TEK3/RTYPE/R-Type/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rtype_ecs

# Build rule for target.
rtype_ecs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtype_ecs
.PHONY : rtype_ecs

# fast build rule for target.
rtype_ecs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_ecs.dir/build.make CMakeFiles/rtype_ecs.dir/build
.PHONY : rtype_ecs/fast

#=============================================================================
# Target rules for targets named rtype_graphic

# Build rule for target.
rtype_graphic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtype_graphic
.PHONY : rtype_graphic

# fast build rule for target.
rtype_graphic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_graphic.dir/build.make CMakeFiles/rtype_graphic.dir/build
.PHONY : rtype_graphic/fast

#=============================================================================
# Target rules for targets named rtype_server

# Build rule for target.
rtype_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtype_server
.PHONY : rtype_server

# fast build rule for target.
rtype_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/build
.PHONY : rtype_server/fast

src/ecs/main.o: src/ecs/main.cpp.o
.PHONY : src/ecs/main.o

# target to build an object file
src/ecs/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_ecs.dir/build.make CMakeFiles/rtype_ecs.dir/src/ecs/main.cpp.o
.PHONY : src/ecs/main.cpp.o

src/ecs/main.i: src/ecs/main.cpp.i
.PHONY : src/ecs/main.i

# target to preprocess a source file
src/ecs/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_ecs.dir/build.make CMakeFiles/rtype_ecs.dir/src/ecs/main.cpp.i
.PHONY : src/ecs/main.cpp.i

src/ecs/main.s: src/ecs/main.cpp.s
.PHONY : src/ecs/main.s

# target to generate assembly for a file
src/ecs/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_ecs.dir/build.make CMakeFiles/rtype_ecs.dir/src/ecs/main.cpp.s
.PHONY : src/ecs/main.cpp.s

src/ecs/test.o: src/ecs/test.cpp.o
.PHONY : src/ecs/test.o

# target to build an object file
src/ecs/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_ecs.dir/build.make CMakeFiles/rtype_ecs.dir/src/ecs/test.cpp.o
.PHONY : src/ecs/test.cpp.o

src/ecs/test.i: src/ecs/test.cpp.i
.PHONY : src/ecs/test.i

# target to preprocess a source file
src/ecs/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_ecs.dir/build.make CMakeFiles/rtype_ecs.dir/src/ecs/test.cpp.i
.PHONY : src/ecs/test.cpp.i

src/ecs/test.s: src/ecs/test.cpp.s
.PHONY : src/ecs/test.s

# target to generate assembly for a file
src/ecs/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_ecs.dir/build.make CMakeFiles/rtype_ecs.dir/src/ecs/test.cpp.s
.PHONY : src/ecs/test.cpp.s

src/graphical/main.o: src/graphical/main.cpp.o
.PHONY : src/graphical/main.o

# target to build an object file
src/graphical/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_graphic.dir/build.make CMakeFiles/rtype_graphic.dir/src/graphical/main.cpp.o
.PHONY : src/graphical/main.cpp.o

src/graphical/main.i: src/graphical/main.cpp.i
.PHONY : src/graphical/main.i

# target to preprocess a source file
src/graphical/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_graphic.dir/build.make CMakeFiles/rtype_graphic.dir/src/graphical/main.cpp.i
.PHONY : src/graphical/main.cpp.i

src/graphical/main.s: src/graphical/main.cpp.s
.PHONY : src/graphical/main.s

# target to generate assembly for a file
src/graphical/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_graphic.dir/build.make CMakeFiles/rtype_graphic.dir/src/graphical/main.cpp.s
.PHONY : src/graphical/main.cpp.s

src/graphical/test.o: src/graphical/test.cpp.o
.PHONY : src/graphical/test.o

# target to build an object file
src/graphical/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_graphic.dir/build.make CMakeFiles/rtype_graphic.dir/src/graphical/test.cpp.o
.PHONY : src/graphical/test.cpp.o

src/graphical/test.i: src/graphical/test.cpp.i
.PHONY : src/graphical/test.i

# target to preprocess a source file
src/graphical/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_graphic.dir/build.make CMakeFiles/rtype_graphic.dir/src/graphical/test.cpp.i
.PHONY : src/graphical/test.cpp.i

src/graphical/test.s: src/graphical/test.cpp.s
.PHONY : src/graphical/test.s

# target to generate assembly for a file
src/graphical/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_graphic.dir/build.make CMakeFiles/rtype_graphic.dir/src/graphical/test.cpp.s
.PHONY : src/graphical/test.cpp.s

src/server/main.o: src/server/main.cpp.o
.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i
.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s
.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

src/server/test.o: src/server/test.cpp.o
.PHONY : src/server/test.o

# target to build an object file
src/server/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/src/server/test.cpp.o
.PHONY : src/server/test.cpp.o

src/server/test.i: src/server/test.cpp.i
.PHONY : src/server/test.i

# target to preprocess a source file
src/server/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/src/server/test.cpp.i
.PHONY : src/server/test.cpp.i

src/server/test.s: src/server/test.cpp.s
.PHONY : src/server/test.s

# target to generate assembly for a file
src/server/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype_server.dir/build.make CMakeFiles/rtype_server.dir/src/server/test.cpp.s
.PHONY : src/server/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rtype_ecs"
	@echo "... rtype_graphic"
	@echo "... rtype_server"
	@echo "... src/ecs/main.o"
	@echo "... src/ecs/main.i"
	@echo "... src/ecs/main.s"
	@echo "... src/ecs/test.o"
	@echo "... src/ecs/test.i"
	@echo "... src/ecs/test.s"
	@echo "... src/graphical/main.o"
	@echo "... src/graphical/main.i"
	@echo "... src/graphical/main.s"
	@echo "... src/graphical/test.o"
	@echo "... src/graphical/test.i"
	@echo "... src/graphical/test.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/server/test.o"
	@echo "... src/server/test.i"
	@echo "... src/server/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

