name: Deploy Documentation

on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust for mdBook
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install mdBook
      run: cargo install mdbook

    - name: Build mdBook
      working-directory: docs/mdbook
      run: mdbook build

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install doxygen graphviz -y

    - name: Build Doxygen
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs